// source: http://www.jenkinssoftware.com/raknet/manual/reliabilitytypes.html
export enum PacketReliability {
  UNRELIABLE,
  UNRELIABLE_SEQUENCED,
  RELIABLE,
  RELIABLE_ORDERED,
  RELIABLE_SEQUENCED,
  UNRELIABLE_WITH_ACK_RECEIPT,
  UNRELIABLE_SEQUENCED_WITH_ACK_RECEIPT,
  RELIABLE_WITH_ACK_RECEIPT,
  RELIABLE_ORDERED_WITH_ACK_RECEIPT,
  RELIABLE_SEQUENCED_WITH_ACK_RECEIPT,
}
