export const Identifiers = {
  ID_CONNECTED_PING: 0x00,
  ID_UNCONNECTED_PING: 0x01,
  ID_UNCONNECTED_PONG: 0x1c,

  ID_OPEN_CONNECTION_REQUEST_1: 0x05,
  ID_OPEN_CONNECTION_REPLY_1: 0x06,
  ID_OPEN_CONNECTION_REQUEST_2: 0x07,
  ID_OPEN_CONNECTION_REPLY_2: 0x08,
}
