export enum Identifiers {
  CONNECTED_PING,
  UNCONNECTED_PING,
  UNCONNECTED_PING_OPEN_CONNECTION,

  UNCONNECTED_PONG = 0x1c,

  OPEN_CONNECTION_REQUEST_1 = 5,
  OPEN_CONNECTION_REPLY_1,
  OPEN_CONNECTION_REQUEST_2,
  OPEN_CONNECTION_REPLY_2,

  INCOMPATIBLE_PROTOCOL_VERSION = 0x19,
}
