export enum Identifiers {
  CONNECTED_PING,
  UNCONNECTED_PING,
  UNCONNECTED_PING_OPEN_CONNECTION,
  CONNECTED_PONG,

  OPEN_CONNECTION_REQUEST_1 = 0x05,
  OPEN_CONNECTION_REPLY_1,
  OPEN_CONNECTION_REQUEST_2,
  OPEN_CONNECTION_REPLY_2,

  CONNECTION_REQUEST,
  CONNECTION_REQUEST_ACCEPTED,

  ALREADY_CONNECTED = 0x12,
  NEW_INCOMING_CONNECTION,

  DISCONNECT_NOTIFICATION = 0x15,

  INCOMPATIBLE_PROTOCOL_VERSION = 0x19,

  UNCONNECTED_PONG = 0x1c,

  GAME_PACKET = 0xfe,
}
