export const Identifiers = {
  // RakNet related stuff
  GAME_PROTOCOL: 389,
  GAME_VERSION: '1.14.1',

  // Only for internal use, not a MCPE packet
  ID_NOT_SET: -129,

  ID_CONNECTED_PING: 0x00,
  ID_UNCONNECTED_PING: 0x01,
  ID_UNCONNECTED_PONG: 0x1c,

  ID_OPEN_CONNECTION_REQUEST_1: 0x05,
  ID_OPEN_CONNECTION_REPLY_1: 0x06,
  ID_OPEN_CONNECTION_REQUEST_2: 0x07,
  ID_OPEN_CONNECTION_REPLY_2: 0x08,

  ID_CONNECTION_REQUEST: 0x09,
  ID_CONNECTION_REQUEST_ACCEPTED: 0x10,
}
