export enum Protocol {
  MC_VERSION = '1.17.30',
  MC_PROTOCOL = 465,

  UNKNOWN = 0x00,
  LOGIN = 0x01,
  PLAY_STATUS = 0x02,
  SERVER_TO_CLIENT_HANDSHAKE = 0x03,
  CLIENT_TO_SERVER_HANDSHAKE = 0x04,
  RESOURCE_PACKS_INFO = 0x06,
  RESOURCE_PACK_STACK = 0x07,
  RESOURCE_PACK_RESPONSE = 0x08,
  TEXT = 0x09,
  MOVE_PLAYER = 0x13,
  SET_TIME = 0x0a,
  START_GAME = 0x0b,
  ADD_PLAYER = 0x0c,

  UPDATE_ATTRIBUTES = 0x1d,
  TICK_SYNC = 0x17,

  SET_ENTITY_METADATA = 0x27,
  SET_SPAWN_POSITION = 0x2b,

  ADVENTURE_SETTINGS = 0x37,
  LEVEL_CHUNK = 0x3a,
  SET_DIFFICULTY = 0x3c,
  PLAYER_LIST = 0x3f,

  REQUEST_CHUNK_RADIUS = 0x45,
  CHUNK_RADIUS_UPDATED = 0x46,

  CREATIVE_CONTENT = 0x91,
  SET_LOCAL_PLAYER_AS_INITIALIZED = 0x71,
  NETWORK_CHUNK_PUBLISHER_UPDATE = 0x79,
  BIOME_DEFINITION_LIST = 0x7a,

  PACKET_VIOLATION_WARNING = 0x9c,

  // TODO: implement all other identifiers...
  CLIENT_CACHE_STATUS = 0x81,
  NETWORK_SETTINGS = 0x8f,

  PLAYER_FOG = 0xa0,
  ITEM_COMPONENT = 0xa2,
}
