export enum Protocol {
  MC_VERSION = '1.16.220',
  MC_PROTOCOL = 431,

  UNKNOWN = 0x00,
  LOGIN = 0x01,
  PLAY_STATUS = 0x02,
  SERVER_TO_CLIENT_HANDSHAKE = 0x03,
  CLIENT_TO_SERVER_HANDSHAKE = 0x04,
  RESOURCE_PACKS_INFO = 0x06,
  RESOURCE_PACK_STACK = 0x07,
  RESOURCE_PACK_RESPONSE = 0x08,
  START_GAME = 0x0b,

  TICK_SYNC = 0x17,

  LEVEL_CHUNK = 0x3a,

  REQUEST_CHUNK_RADIUS = 0x45,
  CHUNK_RADIUS_UPDATED = 0x46,

  CREATIVE_CONTENT = 0x91,
  SET_LOCAL_PLAYER_AS_INITIALIZED = 0x71,
  NETWORK_CHUNK_PUBLISHER_UPDATE = 0x79,
  BIOME_DEFINITION_LIST = 0x7a,

  // TODO: implement all other identifiers...
  CLIENT_CACHE_STATUS = 0x81,
}
