export enum PlayStates {
  LOGIN_SUCCESS = 0,
  LOGIN_FAILED_CLIENT,
  LOGIN_FAILED_SERVER,
  PLAYER_SPAWN,
  LOGIN_FAILED_INVALID_TENANT,
  LOGIN_FAILED_VANILLA_EDU,
  LOGIN_FAILED_EDU_VANILLA,
  LOGIN_FAILED_SERVER_FULL,
}
